### PR TITLE
updated grub cfg for fedora 34+

### PR DESCRIPTION
**Pull request by ShawonAshraf**
See https://github.com/shvchk/fallout-grub-theme/issues/23

### CODE REVIEW

**Comment by ShawonAshraf** [comment]
I don't have a way to test for CentOS or RHEL. Perhaps someone else can test that? Or we can suggest the users to manually update grub for these distros instead of the script doing it all.

**Comment by ShawonAshraf** [comment]
I'll have to set up a fedora VM. Will check on it this weekend and report back!

**Comment by shvchk** [comment]
Tried in Fedora VM: can confirm that removing lines 113-116 is enough. Will test other distros today and then fix this.

**Comment by shvchk** [comment]
Should be fixed now, see [e843386](https://github.com/shvchk/fallout-grub-theme/commit/e8433860b11abb08720d7c32f5b9a2a534011bca)

**Pull request closed without merging**
