### PR TITLE
EndeavourOS icon

### PR DESCRIPTION
**Pull request by zer0ring**
Hi Jacksaur, thanks for the amber CRT GRUB menu theme, here's an EndeavourOS distro logo icon for you to include if you wish:
endeavouros

### CODE REVIEW

**Comment by Zorrototo** [comment]
Is it me not understanding, or is this PR for another repository (a fork of this repository)?

**Comment by zer0ring** [comment]
Lol it's not just you, I could find no way to make a PR to the fork, every attempt ended up on the main branch so I gave up & just made it.

2 Sep 2022 04:46:23 ®omano ***@***.***>:

**Comment by Zorrototo** [comment]
That makes no sense.

**Comment by zer0ring** [comment]
> That makes no sense.
> 
> //EDIT: If you're using the web interface, and you have a fork of...
> Delete the fork of this project (Fallout GRUB Theme) from GitHub web interface (it is in Settings of the forked repository), then fork the CRT Amber GRUB Theme, and send a PR to the proper repository. Not sure why you can't fork both at same time from web interface, probably a configuration mistake on the Amber fork side.

I haven't forked anything & I don't control Jackosaur's fork.

> You should do things properly as this PR here is not doing anything good.
Thanks, this was my first Github interaction (beyond cloning & installing).

I'll try to close this PR, that's about the only thing I can do, there's no way to interact with the fork i wanted to contribute to, or means of contacting it's author.

**Comment by zer0ring** [comment]
Closed PR as per request due to irrelevance to branch.

**Pull request closed without merging**
